### ISSUE TITLE
ASK: About QoS Treatment

### ISSUE THREAD

**Issue by kholisrag** [mattjhayes/nmeta#110]
qos_treatment:
  default_priority: 0
  constrained_bw: 1
  high_priority: 2
  low_priority: 3

Sir, I want to ask about qos treatment above...
why the constrained_bw < high_priority < low_priority

I think that's to be like this :
constrained_bw < low_priority < high_priority
so the queue number is to be like this :
constrained_bw: 1
low_priority: 2
high_priority: 3

because I think the higher the queue number, the higher the priority...
I want to change it to own policy, but when I read the documentation, I so confused about this...
why low priority queue number is higher the high priority queue number?

Thanks for your attention and aswer sir...

**Comment by mattjhayes** [comment]
Hi, thanks for the feedback. The QoS queue numbers are arbitrary. They instruct the switch as to which queue the packet/flow should traverse. It relies on queues being configured appropriately on the switches, which must be done separately to nmeta. I'll update the documentation to make this clear.

**Comment by kholisrag** [comment]
So it's like that... I think it's configure in nmeta...
I use ovs, so I should config with ovs-vsctl queue and qos... thanks...

**Comment by mattjhayes** [comment]
I'm using Open vSwitch, which uses tc in the Linux kernel.

Here's an example config that sets QoS on interfaces eth1 and eth2 with queue 0 unrestricted and queue 1 restricted to max rate of 100Kbps:

```
sudo ovs-vsctl clear Port eth1 qos
sudo ovs-vsctl clear Port eth2 qos
sudo ovs-vsctl --all destroy qos

sudo ovs-vsctl -- set Port eth1 qos=@newqos \
-- --id=@newqos create QoS type=linux-htb other-config:max-rate=1000000000 queues=0=@q0,1=@q1 \
-- --id=@q0 create Queue other-config:max-rate=1000000000 \
-- --id=@q1 create Queue other-config:max-rate=100000

sudo ovs-vsctl -- set Port eth2 qos=@newqos \
-- --id=@newqos create QoS type=linux-htb other-config:max-rate=1000000000 queues=0=@q0,1=@q1 \
-- --id=@q0 create Queue other-config:max-rate=1000000000 \
-- --id=@q1 create Queue other-config:max-rate=100000
```

You'll need to come up with a configuration to suit your particular needs

**Comment by kholisrag** [comment]
Thanks... I just read and try the ovs documentation, it' work, like yours...
